name: Release

on: 
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: cycjimmy/semantic-release-action@v2
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo ${{ steps.release.outputs.new_release_version }}
