name: Env

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - run: |
        echo $(git log --oneline)
        echo $(git tag --points-at HEAD --sort=-v:refname)
        echo $(git rev-parse --short HEAD)
