name: TestAction

on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        description: 'Command Name'
        default: ''
      group:
        required: true
        description: 'Group Name'
        default: 'a1'

env:
  ENVIRONMENT: foo
  USERS: '["bsoo", "evalphobia"]'
  WORKFLOW_USER: "\"${{ github.actor }}\""
jobs:
  run:
    name: run cmd
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: if not users
        if: "!contains(env.USERS, env.WORKFLOW_USER)"
        run: echo "NOT contains ${{ env.WORKFLOW_USER }}"

      - name: if users
        if: "contains(env.USERS, env.WORKFLOW_USER)"
        run: echo "Contains ${{ env.WORKFLOW_USER }}"

      - name: set params
        run: >
          _PARAMS=`echo | perl -ne '@a = split(/\s+/, $_); foreach (@a) {$_ = "\"$_\""}; print(join(", ", @a))'`
          echo "PARAMS=$_PARAMS" >> $GITHUB_ENV

      - name: Run Command
        run: echo ${{ env.ENVIRONMENT }} '["bash", "param1", ${{ env.PARAMS }}]'
